[package]
name = "mgl"
type = "static"
version = "1.1.0"
platforms = ["posix"]

[define]
MGL_LIBDECOR = "1"

[config]
ignore_dirs = ["build"]
expose_include_dirs = ["include"]

[dependencies]
x11 = ">=0.5"
xrender = ">=0.5"
xrandr = ">=0.5"
wayland-client = ">=1"
wayland-egl = ">=15"
wayland-cursor = ">=1"
xkbcommon = ">=1"
libdecor-0 = ">=0"
pangoft2 = ">=1"
gio-2.0 = ">=2"